### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Lobox1** [JamzaSK/TWInventoryReloaded#1]
Hi programmer,
  from after the last update a warning continues to appear in which it says that there is a problem and to open the consol, at the opening of the consol a message appears in which it says that it is in error. In addition to this problem, the description of the object no longer appears when the cursor is moved over any object in the inventory. In addition to this other problem, the group itelegrams appear with a completely white window. This problem as well as from me was encountered by other players in multiple game worlds.
I apologize for the English, I used the google translator.

Sincerely,

Lobox Player of The-West Old West Ita

**Comment by JamzaSK** [comment]
Hey, whats your browser and do you use the Toolkit script?

**Comment by Lobox1** [comment]
Using Chrome with tampermonkeychrome

**Comment by pepe1000** [comment]
Translation to Spanish:

{
  "script_name": "TW Inventory Reloaded",
  "translate": "Español (es)",
  "invent": "Inventario",
  "script_version": "Versión",
  "script_revision": "Revisión",
  "changes": "¿Qué hay de nuevo?",
  "translator": "traductor: pepe100",
  "language": "Idioma",
  "download": "Descargar aquí",
  "no_ads": "¡Sin anuncios!",
  "ads": "Anuncios",
  "update_message": "¡El script ha sido actualizado! Por favor, descargue la última versión.",
  "donate_title": "Apoyando el desarrollo",
  "donate_text": "Si desea ayudar al desarrollo, o simplemente mostrar su aprecio, utilice una de las siguientes formas:",
  "donate_paypal": "Invítanos a un Café",
  "donate_ingame": "Danos un Regalo",
  "tyty": "Gracias",
  "inventory": {
    "adventures": "Aventuras",
    "labor_points": "Puntos de Trabajo (PT)",
    "duels": "Duelos",
    "energy": "Energía",
    "skills": "Habilidades",
    "fort_battles": "Batallas",
    "speed": "Velocidad",
    "health": "Puntos de Salud",
    "events": "Eventos",
    "unpacks": "Desempaquetar",
    "crafted_items": "Artículos elaborados",
    "field_cook": "Cocinero de Campo",
    "tonic_peddler": "Vendedor de Tónicos",
    "blacksmith": "Herrero",
    "master_saddler": "Maestro de Guarnición",
    "recipes": "Recetas",
    "quest_items": "Productos de búsqueda",
    "work_items": "Productos de trabajo",
    "equipment": "Conjunto con Bonus de productos",
    "coll_cards": "Tarjetas de colección",
    "craft_cards": "Tarjetas artesanales",
    "from_set": "Elementos de Conjunto",
    "upgraded": "Actualizado",
    "useable": "Utilizable",
    "premium": "Premium",
    "xp": "Experiencia",
    "luck_money": "Suerte y Dinero",
    "crafting": "Elaboración",
    "buffs": "Buffs",
    "others": "Sin categorizar",
    "sets": "Lista de elementos de Conjunto",
    "twir_menu": "Menú",
    "bonds_money": "Bonos y dólares",
    "waytime_shortening": "Acortar tiempo viaje",
    "work_motivation": "Motivación trabajo",
    "duel_motivation": "Motivación duelo",
    "avatar_part": "Parte de avatar"
  },
  "tooltips": {
    "jobdrop": "Obtenibles desde trabajos",
    "not_auctionable": "No subastables",
    "upgradeable": "Actualizables",
    "craftable": "Puede ser elaborado",
    "missing_items": "Objetos perdidos",
    "owned_items_bonus": "Bonus (objetos propios)",
    "partial_items_bonus": "Set Bonus",
    "market_price": "Precio Mercado",
    "suggested_price": "Precio sugerido",
    "minimal_price": "Mín",
    "maximal_price": "Máx",
    "listings": "listados",
    "items": "artículos",
    "items_short": "pcs",
    "seen": "Visto $1 vez",
    "last_seen": "Visto por última vez",
    "average": "Promedio",
    "average_since": "Promedio $1 días",
    "each": "cada"
  },
  "organizing": {
    "invert_text": "Mostrar / Ocultar diferentes elementos basados en un filtro seleccionado",
    "invert": "Invertir",
    "none": "Ninguno",
    "all_items": "mostrar todos",
    "save_permanent": "Recuerda",
    "bonus": "Bonus",
    "bonus_search": "Buscar Bonus",
    "show": "Mostrar",
    "upgradeable": "Actualizable",
    "sellable": "Vendible",
    "auctionable": "Subastable",
    "tradeable": "Comercializable",
    "droppable": "Obtenibles",
    "duplicates": "Duplicados",
    "gender": "Personaje",
    "collectibles": "Coleccionables",
    "submit": "Enviar",
    "sort_by": "Ordenar por",
    "filter": "Filtrar",
    "sort_up": "Ascendente",
    "sort_down": "Descendente",
    "sort_ab": "Alfabética",
    "sort_buyprice": "Precio Compras",
    "sort_sellprice": "Precio Venta",
    "sort_id": "ID Objeto",
    "sort_reqlvl": "Nivel requerido",
    "sort_upglvl": "Actualizar nivel",
    "sort_mindamage": "Daño Mín.",
    "sort_maxdamage": "Daño Máx.",
    "sort_quantity": "Tamaño de pila",
    "sort_setname": "Nombre de Conjunto",
    "sort_marketprice": "Precio (mercado)",
    "value": "Valor"
  },
  "stats": {
    "stats": "Estadísticas",
    "all_collected": "Todos",
    "sales_value": "Valor Ventas",
    "quantities": "Cantidades",
    "total_buy_price": "Total precio compras",
    "total_sell_price": "Total precio venta",
    "distinct_items": "Artículos distintos",
    "distinct_products": "Productos distintos",
    "wear": "Equipados",
    "backpack": "Mochila",
    "items": "Artículos",
    "products": "Productos",
    "item": "Artículo",
    "product": "Producto",
    "recipes": "Recetas",
    "dropped": "Obtenibles",
    "duplicates": "Duplicados",
    "set_and_bonus": "Conjunto con Bonus productos",
    "job_products": "Productos de trabajo",
    "quest_products": "Productos de búsquedas",
    "buffs": "Buffs",
    "crafting": "Elaboración",
    "other_products": "Otros productos",
    "most_expensive": "Más caro",
    "most_pieces": "Más piezas",
    "item_set": "Artículos de conjuntos",
    "owned_sets": "Conjuntos propios",
    "completed_sets": "Conjuntos completos",
    "count_text": "La cantidad de artículos en el inventario",
    "shot": "Armas de duelo",
    "hand": "Armas contundentes",
    "set_menu_error": "Abrir lista de elementos de conjuntos primero para calcular",
    "shiftinfo": "Presionar [Tecla-Shift] para mostrar más información",
    "average": "Promedio",
    "total_market_price": "Total precio mercado"
  },
  "market_watcher": {
    "add_name": "Observador de Mercado",
    "seen": "algunos de los artículos observados han sido visto",
    "seen_more": "y $1 artículos vistos ",
    "add_item": "añadir artículo",
    "offer_count": "y $1 anuncios",
    "time_left": "tiempo restante",
    "price": "precio",
    "max_price": "Máx. precio",
    "item_id": "ID artículo",
    "bid": "oferta"
  },
  "features": {
    "preferences": "Preferencias",
    "inventory_menus": "Inventario/ Menús",
    "window_title": "título principal mejorado",
    "window_minititle": "título inferior mejorado",
    "empty_opacity": "vacio a la opacidad",
    "item_counts": "recuento de artículos",
    "sets_counts": "recuento de artículos de conjunto",
    "sets_color": "color para conjuntos completos",
    "event": "visualizar evento",
    "popup_tooltips": "Información sobre herramientas",
    "item_id": "id artículo",
    "job_name": "nombre de trabajo",
    "item_crafting": "elaboración de artículo",
    "recipe_name": "nombre receta",
    "short_currency": "formato de moneta corto",
    "partial_bonus": "bonificación parcial",
    "market_watcher": "observador de mercado",
    "set_pieces": "piezas sueltas",
    "update_prices": "seguimiento precios",
    "market_alert": "Seguimiento de artículo",
    "alert_sound": "sonido de alerta",
    "trader": "nivel de comerciante",
    "market_collector": "coleccionista de mercado",
    "sleep": "sueño directo",
    "npc": "localizador NPC",
    "profile": "Perfiles jugador",
    "rank_bar": "mejores 3 rangos",
    "craft_points": "puntos oficio",
    "market_watcher_all": "precio mercado (todos artículos)",
    "forts": "Fuertes y Batallas de Fuertes",
    "travel_button": "botón viaje al fuerte",
    "topic": "topic del chat preparación batalla",
    "online_status": "mostrar estado conectado",
    "ranks": "mostrar rangos"
  },
  "keyWords": {
  "xmas": [
    "Navidad",
    "Venta de vacaciones"
  ],
  "valentine": "San Valentín",
  "independance": "Día de la Independencia",
  "dotd": [
    "Día de los Muertos",
    "Día de los Muertos"
  ],
  "easter": "Pascua",
  "oktoberfest": "Oktoberfest"
},
  "menulink": {
    "add_name": "Barra del Menú enlaces",
    "market": "Coleccionista Mercado",
    "npc": "Dadores búsquedas",
    "nearest": "Hotel más cercano",
    "nearest_five": "Hotel de 5 estrellas más cercano",
    "sleep": "Encontrar una cama",
    "premium_bids": "Recoger todas las pujas",
    "premium_offers": "Recoger todas las ofertas"
  },
  "ranking": {
    "add_name": "Barra rangos",
    "rank": "Rango",
    "duels": "Duelos",
    "won": "Ganados",
    "lost": "Perdidos",
    "diff": "Diferencia",
    "fb": "Batallas de Fuertes",
    "dd": "Daño infligido",
    "taken": "Aciertos recibidos",
    "dodges": "Eludidoss",
    "crafting": "Elaboración",
    "learnt": "Aprendida",
    "points": "Puntos",
    "crafted": "Elaborados",
    "construction": "Construcción",
    "fair": "Feria ambulante",
    "stage_ups": "Niveles subidos",
    "mpi": "Aventuras",
    "ko": "KOs",
    "games": "Juegos",
    "rg": "Abandonos"
  },
  "informative": {
    "error404": "No se encontraron artículos de este tipo",
    "error": "Parámetros inválidos.",
    "sucess": "Cambiado con éxito.",
    "bs_limit": "El límite es de 5 habilidades.",
    "storage_error": "¡El almacenamiento local no está permitido!",
    "no_sets": "No posee ningún conjunto",
    "years": "hace $1 años",
    "year": "year",
    "months": "hace $1 meses",
    "days": "hace $1 días",
    "hours": "hace $1 horas",
    "minutes": "hace $1 minutos",
    "seconds": "hace $1 segundos",
    "valid_id": "$1 no es un ID de artículo válido",
    "valid_auctionable": "Artículo $1 no es subastable",
    "valid_defined": "Artículo $1 ya está vigilado",
    "valid_max": "No puedes observar más de 50 artículos ",
    "search": "Buscar artículos, conjuntos, eventos, habilidades, ... o buscar $kw",
    "keyword": "palabra clave",
    "error_wait": "Por favor espere hasta que se complete la búsqueda",
    "error_other": "Ha ocurrido un error, por favor abra la consola para más detalles.",
    "distance": "Distancia",
    "error_hotel": "No se encontró habitación de hotel",
    "error_npc": "No se encontraron npc",
    "error_market": "No se encontraron subastas terminadas",
    "travel_fort": "Viaje al fuerte"
  }
}
