### ISSUE TITLE
TW inventory reloaded stop working after 2.157

### ISSUE THREAD

**Issue by THouGHT4ReaL** [JamzaSK/TWInventoryReloaded#11]
After your last upgrade the script stop working on firefox

**SyntaxError: "JSON.parse: unexpected character at line 1 column 1 of the JSON data"
    find_MarketData https://en13.the-west.net/game.php:253
    init https://en13.the-west.net/game.php:186
    init https://en13.the-west.net/game.php:508
game.php:407:154

 TWIR version: 2.157 on 2.101, locale: en_DK**

I dont know if i done something wrong but before the update all working fine.

Give me a solution if it's possible

**Comment by JamzaSK** [comment]
Hey, type into console:  ` localStorage.removeItem("twir_marketData") ` and `localStorage.removeItem("twir_marketDataJunk")`.  What is your browser?

**Comment by THouGHT4ReaL** [comment]
Thx for you response. My browser is Firefox

**Comment by JamzaSK** [comment]
For now try to remove market data and if the problem persists use Opera/Chrome browser. I will try to fix this issue in next version.

**Comment by THouGHT4ReaL** [comment]
the problem is solved temporarily but if i close the browser and open it again the pop up box "an error occured open console for details" or something like that appears again and i have to do what you say previously again and again for all character each by each.

**Comment by JamzaSK** [comment]
So it was only firefox problem?
