### ISSUE TITLE
Issues (Up-to-date)

### ISSUE THREAD

**Issue by SharpyTr** [JamzaSK/TWInventoryReloaded#12]
The chat messages which have linked items became invisible to the players who are using the Script.
+
Can't open the Telegrams which have even one of those item links.

Perfect timing as the Event items just became Auctionable and especially need Market watcher more than ever :/

Btw;
Being able to mass-tele the Other FF side (like Defenders, if u are an Attacker) via the FF screen doesn't feel right.

**Comment by SharpyTr** [comment]
Well apparently can't Sort the players by "At the Fort" (Or Not) with the script anymore.
Somehow it overwrites the TW-DB's that feature.

**Comment by JamzaSK** [comment]
Prop fixed now, but where is that TWDB feature? I cant see it

**Comment by SharpyTr** [comment]
Like this
http://prntscr.com/oqwpsj
http://prntscr.com/oqwpye < There is also orange for "Near Fort"

**Comment by SharpyTr** [comment]
Okay.. Thanks for fixing all those annoying bugs and all.

Also thanks for cool FF features as well but maybe u shouldn't get into it much anymore.. Lots of things are covered by other scripts already.

For example I see you added a "Hover over" feature that is showing the person's damage and it's cool but there is some sort of sequential Nick Pop-up animation thing going on when you do mouse over few players one after another and it's a tad annoying to wait it end and finally get to see the "last" person u left your mouse on.

I mean when I click on a person I already see the damage etc values.. (Think it's "Toolkit" one)

**Comment by SharpyTr** [comment]
Believe you already removed those but there still might be some other bugs?
https://forum.the-west.net/index.php?threads/forbidden-userscript-tw-inventory-reloaded.58523

**Comment by SharpyTr** [comment]
idk what is this or why it happens :/
http://prntscr.com/roroll

cant cancel them or anything and i dont wanna use cancel all option :/
