### ISSUE TITLE
Number of Inventory Columns

### ISSUE THREAD

**Issue by chad4359** [JamzaSK/TWInventoryReloaded#13]
Any chance we might see an option to reduce the number of columns in the inventory?  I really enjoy so many of the other features you provide but I really do not need to have 11 columns, 4 or 5 is plenty for me.

**Comment by JamzaSK** [comment]
Hey, you mean columns in menu?

**Comment by chad4359** [comment]
I mean the number of columns in the inventory window.  Examples https://prnt.sc/p1dw9h  https://prnt.sc/p1dwl6

**Comment by chad4359** [comment]
Any progress on this?  Is is a possibility in the future?

**Comment by chad4359** [comment]
So I am the only person who doesn't want the inventory bag to cover the entire screen?
