### ISSUE TITLE
Stop using [fort_battlepage => getPlayerDatasheet]

### ISSUE THREAD

**Issue by lpd-au** [JamzaSK/TWInventoryReloaded#14]
This endpoint is deprecated and will be going away soon. In the meantime, while you rewrite your script, please read from and save to `FortBattle.characterCache` in the same way `FortBattle.flashShowCharacterInfo` does.

**Comment by SharpyTr** [comment]
is this related with info pop-ups when u hover over players? man isn't that annoying.
