### ISSUE TITLE
ver 2.185 and 2.186 not work

### ISSUE THREAD

**Issue by Kret33n** [JamzaSK/TWInventoryReloaded#16]
last two update not work, last worked version is 2.184 :(
http://xnova.cz/TWIR.jpg
chrome + tampermonkey

**Comment by JamzaSK** [comment]
Hey, what scripts do you have?

Jamza

**Comment by JamzaSK** [comment]
Fixed in 2.187, rev 14. Thanks for report!

**Comment by SharpyTr** [comment]
not related but 2.187 keep giving update notif on chat altho i did days ago..
