### ISSUE TITLE
Version 2.04-2.121 bug

### ISSUE THREAD

**Issue by GhedoC** [JamzaSK/TWInventoryReloaded#19]
http://prntscr.com/rqneju
Some of the items and texts are rotated. Please fix this. Thanks!

**Comment by SharpyTr** [comment]
I believe it was inno's april 1st "joke"

**Comment by GhedoC** [comment]
:)) thanks for solving it. Great job with the script!

sâm., 11 apr. 2020, 23:16 JamzaSK <notifications@github.com> a scris:
