### ISSUE TITLE
Inventory not loading

### ISSUE THREAD

**Issue by GhedoC** [JamzaSK/TWInventoryReloaded#24]
https://prnt.sc/s7t6bi
Hi there!
After a few days of oscillation between working and not working, now this is an issue that appears every time. Please fix this!

**Comment by Drobek99** [comment]
Hi . I have the same problem .
![image](https://user-images.githubusercontent.com/64538428/80602845-ec40ff00-8a2f-11ea-8f02-b560f8de4f6f.png)

**Comment by TomRobert** [comment]
Me too:
`TypeError: Inventory.addedCategories is undefined`

**Comment by fredtams** [comment]
pareil pour moi et j'ai déjà signaler et pas de réponse de leur part .....

**Comment by JamzaSK** [comment]
Hey, do you still have this problem? I've never seen it before.

J

**Comment by LARROC** [comment]
Hello All -  I am having the same issue as Drobek99 my inventory keeps loading but never does. Any fix for this?

**Comment by JamzaSK** [comment]
Please let me know if this has been fixed in version 2.198. And sorry for the late answer, I was busy.

J.

**Comment by LARROC** [comment]
Thanks for following up, it has been fixed

Best Regards,

Fabian

**Comment by Drobek99** [comment]
All is fixed and work nice. 
            
          
     
      
       
        Dnia 12 lipca 2020 21:26 JamzaSK &lt;notifications@github.com&gt; napisał(a):
       
    
       
         
 Please let me know if this has been fixed in version 2.198. And sorry for the late answer, I was busy. 
 J.
