### ISSUE TITLE
Freezing Effect

### ISSUE THREAD

**Issue by SharpyTr** [JamzaSK/TWInventoryReloaded#25]
Is there a way to somehow get rid of this freezing effect whenever market watcher finishes its searching?

It's horrible especially during Battles.. I mean I know we can Disable it but yea..

**Comment by JamzaSK** [comment]
Hey, yes, I know about this problem. In v. 2.196 was added limit to maximal number of scans in the local storage and I'm still working on better way how to fix this.

J.
