### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by GabrielBdeC** [JamzaSK/TWInventoryReloaded#26]
I did the job for pt-br and some quotes of pt.

Do I have do to something? Submit or whatever?

**Comment by JamzaSK** [comment]
Hey, thank you so much, I will add your translation tomorrow :)

J.

**Comment by JamzaSK** [comment]
Added.

**Comment by GabrielBdeC** [comment]
I'll improve it with the context when I get some time and I return it here.

Also, if you need a programmer, I can help.

**Comment by JamzaSK** [comment]
Thanks! and If you want to help us with programming, email me at 97jamza@gmail.com.  :)
