### ISSUE TITLE
links

### ISSUE THREAD

**Issue by radu47a** [JamzaSK/TWInventoryReloaded#3]
hello, i have an issue, it doesn't show me the item links in chat anymore. as long as i deactivate it i can use the links again. i have no idea why

**Comment by Br41n88** [comment]
Additional info: 
In fact the whole chat line with the link doesn't show up at all! (shows up for everyone else though)
The issue is with the TWIR.enhancedChatInfo() function. At least i think so because temporarily disabling it in the code fixed it ;-)
