### ISSUE TITLE
Market Watcher Issue

### ISSUE THREAD

**Issue by SharpyTr** [JamzaSK/TWInventoryReloaded#9]
With the latest Update Market Watcher stopped showing up the search results on the left hand side.

Apparently that's because Search is never ending for some reason (When I try to remove something from the list it tells me to wait for it to complete but it never does)

Infinite loop? :P

**Comment by JamzaSK** [comment]
Hey, wait for 2.157.. I did few changes in MW so maybe it will fix it :)

**Comment by JamzaSK** [comment]
And I think it was problem with full scan DB.. local storage is sadly limited to 5Mb but I have fixed this issue in 2.157

**Comment by SharpyTr** [comment]
Update did fixed it indeed! :)

(Couldnt figure a way to search for entire sets yet. How we find Set ID anyway)
